/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as PharmacyRouteImport } from './routes/pharmacy'
import { Route as PharmaciesRouteImport } from './routes/pharmacies'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as EmailSentRouteImport } from './routes/email-sent'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RequestsIndexRouteImport } from './routes/requests.index'
import { Route as PharmacyIndexRouteImport } from './routes/pharmacy.index'
import { Route as RequestsIdRouteImport } from './routes/requests.$id'
import { Route as PharmacySettingsRouteImport } from './routes/pharmacy.settings'
import { Route as PharmacyOrdersRouteImport } from './routes/pharmacy.orders'
import { Route as PharmacyInventoryRouteImport } from './routes/pharmacy.inventory'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const PharmacyRoute = PharmacyRouteImport.update({
  id: '/pharmacy',
  path: '/pharmacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PharmaciesRoute = PharmaciesRouteImport.update({
  id: '/pharmacies',
  path: '/pharmacies',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailSentRoute = EmailSentRouteImport.update({
  id: '/email-sent',
  path: '/email-sent',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsIndexRoute = RequestsIndexRouteImport.update({
  id: '/requests/',
  path: '/requests/',
  getParentRoute: () => rootRouteImport,
} as any)
const PharmacyIndexRoute = PharmacyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PharmacyRoute,
} as any)
const RequestsIdRoute = RequestsIdRouteImport.update({
  id: '/requests/$id',
  path: '/requests/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PharmacySettingsRoute = PharmacySettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => PharmacyRoute,
} as any)
const PharmacyOrdersRoute = PharmacyOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => PharmacyRoute,
} as any)
const PharmacyInventoryRoute = PharmacyInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => PharmacyRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/email-sent': typeof EmailSentRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pharmacies': typeof PharmaciesRoute
  '/pharmacy': typeof PharmacyRouteWithChildren
  '/products': typeof ProductsRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/pharmacy/inventory': typeof PharmacyInventoryRoute
  '/pharmacy/orders': typeof PharmacyOrdersRoute
  '/pharmacy/settings': typeof PharmacySettingsRoute
  '/requests/$id': typeof RequestsIdRoute
  '/pharmacy/': typeof PharmacyIndexRoute
  '/requests/': typeof RequestsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/email-sent': typeof EmailSentRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pharmacies': typeof PharmaciesRoute
  '/products': typeof ProductsRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/pharmacy/inventory': typeof PharmacyInventoryRoute
  '/pharmacy/orders': typeof PharmacyOrdersRoute
  '/pharmacy/settings': typeof PharmacySettingsRoute
  '/requests/$id': typeof RequestsIdRoute
  '/pharmacy': typeof PharmacyIndexRoute
  '/requests': typeof RequestsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/email-sent': typeof EmailSentRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pharmacies': typeof PharmaciesRoute
  '/pharmacy': typeof PharmacyRouteWithChildren
  '/products': typeof ProductsRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/pharmacy/inventory': typeof PharmacyInventoryRoute
  '/pharmacy/orders': typeof PharmacyOrdersRoute
  '/pharmacy/settings': typeof PharmacySettingsRoute
  '/requests/$id': typeof RequestsIdRoute
  '/pharmacy/': typeof PharmacyIndexRoute
  '/requests/': typeof RequestsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/email-sent'
    | '/forgot-password'
    | '/login'
    | '/pharmacies'
    | '/pharmacy'
    | '/products'
    | '/reports'
    | '/reset-password'
    | '/settings'
    | '/pharmacy/inventory'
    | '/pharmacy/orders'
    | '/pharmacy/settings'
    | '/requests/$id'
    | '/pharmacy/'
    | '/requests/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/email-sent'
    | '/forgot-password'
    | '/login'
    | '/pharmacies'
    | '/products'
    | '/reports'
    | '/reset-password'
    | '/settings'
    | '/pharmacy/inventory'
    | '/pharmacy/orders'
    | '/pharmacy/settings'
    | '/requests/$id'
    | '/pharmacy'
    | '/requests'
  id:
    | '__root__'
    | '/'
    | '/email-sent'
    | '/forgot-password'
    | '/login'
    | '/pharmacies'
    | '/pharmacy'
    | '/products'
    | '/reports'
    | '/reset-password'
    | '/settings'
    | '/pharmacy/inventory'
    | '/pharmacy/orders'
    | '/pharmacy/settings'
    | '/requests/$id'
    | '/pharmacy/'
    | '/requests/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EmailSentRoute: typeof EmailSentRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PharmaciesRoute: typeof PharmaciesRoute
  PharmacyRoute: typeof PharmacyRouteWithChildren
  ProductsRoute: typeof ProductsRoute
  ReportsRoute: typeof ReportsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  RequestsIdRoute: typeof RequestsIdRoute
  RequestsIndexRoute: typeof RequestsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pharmacy': {
      id: '/pharmacy'
      path: '/pharmacy'
      fullPath: '/pharmacy'
      preLoaderRoute: typeof PharmacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pharmacies': {
      id: '/pharmacies'
      path: '/pharmacies'
      fullPath: '/pharmacies'
      preLoaderRoute: typeof PharmaciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email-sent': {
      id: '/email-sent'
      path: '/email-sent'
      fullPath: '/email-sent'
      preLoaderRoute: typeof EmailSentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests/': {
      id: '/requests/'
      path: '/requests'
      fullPath: '/requests/'
      preLoaderRoute: typeof RequestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pharmacy/': {
      id: '/pharmacy/'
      path: '/'
      fullPath: '/pharmacy/'
      preLoaderRoute: typeof PharmacyIndexRouteImport
      parentRoute: typeof PharmacyRoute
    }
    '/requests/$id': {
      id: '/requests/$id'
      path: '/requests/$id'
      fullPath: '/requests/$id'
      preLoaderRoute: typeof RequestsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pharmacy/settings': {
      id: '/pharmacy/settings'
      path: '/settings'
      fullPath: '/pharmacy/settings'
      preLoaderRoute: typeof PharmacySettingsRouteImport
      parentRoute: typeof PharmacyRoute
    }
    '/pharmacy/orders': {
      id: '/pharmacy/orders'
      path: '/orders'
      fullPath: '/pharmacy/orders'
      preLoaderRoute: typeof PharmacyOrdersRouteImport
      parentRoute: typeof PharmacyRoute
    }
    '/pharmacy/inventory': {
      id: '/pharmacy/inventory'
      path: '/inventory'
      fullPath: '/pharmacy/inventory'
      preLoaderRoute: typeof PharmacyInventoryRouteImport
      parentRoute: typeof PharmacyRoute
    }
  }
}

interface PharmacyRouteChildren {
  PharmacyInventoryRoute: typeof PharmacyInventoryRoute
  PharmacyOrdersRoute: typeof PharmacyOrdersRoute
  PharmacySettingsRoute: typeof PharmacySettingsRoute
  PharmacyIndexRoute: typeof PharmacyIndexRoute
}

const PharmacyRouteChildren: PharmacyRouteChildren = {
  PharmacyInventoryRoute: PharmacyInventoryRoute,
  PharmacyOrdersRoute: PharmacyOrdersRoute,
  PharmacySettingsRoute: PharmacySettingsRoute,
  PharmacyIndexRoute: PharmacyIndexRoute,
}

const PharmacyRouteWithChildren = PharmacyRoute._addFileChildren(
  PharmacyRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EmailSentRoute: EmailSentRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PharmaciesRoute: PharmaciesRoute,
  PharmacyRoute: PharmacyRouteWithChildren,
  ProductsRoute: ProductsRoute,
  ReportsRoute: ReportsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  RequestsIdRoute: RequestsIdRoute,
  RequestsIndexRoute: RequestsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
